[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin", "googleapis", "@remotion/lambda"]
  ignored_node_modules = ["remotion", "@remotion/cli", "@remotion/renderer", "react", "react-dom"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
